version = 1

[macos.dock]
autohide = true
orientation = "right"
tilesize = 64
autohide-time-modifier = 0.0
autohide-delay = 0.0
show-recents = false
mineffect = "scale"
static-only = false
scroll-to-open = true

[macos.defaultsRaw]
"com.apple.dock.workspaces-auto-swoosh" = { value = 0, type = "int" }
"com.apple.dock.dashboard-in-overlay" = { value = true, type = "bool" }
"com.apple.dock.expose-animation-duration" = { value = 0.0, type = "float" }
"com.apple.dock.showhidden" = { value = true, type = "bool" }
"com.apple.SystemUIServer.menuExtras" = { value = "/System/Library/CoreServices/Menu Extras/Clock.menu", type = "string" }
