version = 1

[macos.dock]
# Reset autohide to system default (omitting sets no value)
# autohide = 

[macos.defaultsRaw]
# Method 1: Use "default" string to reset
"com.apple.dock.workspaces-auto-swoosh" = { value = "default", type = "string" }

# Method 2: Use explicit reset flag
"com.apple.dock.expose-animation-duration" = { value = 0.1, type = "float", reset = true }

# Method 3: Use null value (commented out since TOML doesn't support null directly)
# "com.apple.dock.launchanim" = { value = null, type = "bool" }

# Regular values work as normal
"com.apple.dock.minimize-to-application" = { value = true, type = "bool" }